language: node_js
node_js:
  - "10"
jobs:  
  include:
    - stage: "Tests"
      name: "Lint"
      script: "npm run lint"
    - name: "Tests"
      script: "npm run test"
    - stage: "Release"
      name: "Semantic release"
      script: "npm run release"
      if: branch = master
